language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: cx4J4vk3LMJyJbNxMYFUZOXApsbhuM3fPbRu3DyBSZf0DGZnd32+5cAThYq8+8MCBmCn8NXKr4DbmWineS72D1anETmCRcKKk4EThOgCIPMuuFoYdh+GQj8A260yZA+cY3C7WI/nogMx5wOoElUtcy2bIf+MBmisuEW8PeZ1x72JfW6AkxKKY5Rrt9CGxziL6X6K/B1PlpItumF6exxRfG4IwC0dFYXvkJ2sXCvCvHy6LKtnGfbZhl0WnT8v6e2N15zCf7dQS8IrA6oi8sGg6E9w5lDZVFnwYkMboiYRFLQ4CUZTFQYtoVJSfeNqrgZG9jRipSON75OH3QR171hrUunpOra+C/lOO4rNoKxOL0Z9Z5oYkV0Vg8c3rCi1dCp7AuLF6gkAvhGJi/oz+ZZTCZYkYFBkjqZqPPbSZs/UbGqL4h/S7K9iLGdcZ7Rjhwr317drGJvxKYz08EG3i53DwcV7jaIxSzbMZhmHnq6hEl6/zYXwQePhy0r5HcCpeUs4N/GtRcHi+OBiK68k4vju3NJpf9HVlTA0iUYPceLXYDTH4idTFPdIA0UHkPFmf2yUT2Q+XcWO6ZLFwEBZNXE/3DIVXtSw1X/MIqG/tHqBSwI2xbl8riBdLFqurxQdz+EH6bd36Io8FasA+OB9CfeJuOo/0QjoF/HVBzDWAVvyuq8=
  - secure: GzBDwWuk7VDU7Be0qYJDvEQaXzzA2tAQ4aLlxwX6QZPWW+ib1eSDoru6n+lSOcr78uIT5f7932Ye8rlJuM7bgdhibdC7MNrPwBflwjcPLpCEdnG+LZi8E45NCtQMqA5d5U2DoNBq4Vz7utyQrnwcWtplPEBXIx+XcqkzmrvtwTESOAIXU29NQszJxfLwDrQdwMA5PtLH4eM+1a4KoARn1VUqJ4xA0VLn3Q22te4Z/Jo1F2Q7j5NZHHfVjfz6EDbTtdXxaN8B5TE+i3guDMV86f88h9X4+2na6hGgpzBEYDjrb4X30qAaHqrnK26aVRTTyFHFEFqOXStsHbYYHJ+jMRiZ/PVUNDDTbQ4oYm5Xmi8NNR7PdxTo5dIbGG7ChZ/FlMMLXHP2auueaUzA8eDIwXDmBDxCVmEUKezQjyUUaKptFdE0a3hIf1UG9VGFsXNeuRQbi1MxqQbqfI+VXO2Rn+cxkdDJ2ZGIMjLoPCcAC7XrQWdDDnPIh3GKDcgyVEkRYd7MFcha1QIUfXlhnTOncnDqRS04YviwOOssC6xWVMD0zwU7kcyWvzptlxEM96zMPBGGoquPUHMv6BGZfKnQ3AkgKTeNgZ5oAL0LLXrZC0lUr7AbZL5SrGCVbX5CDPVmAA3dJqrS0u/MxzmLVBdVw2tnQPSJ6clbIiriVXzdEJs=
script:
- molecule --debug test
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_cfbf5d29b26f_key -iv $encrypted_cfbf5d29b26f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv travis /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/travis
